export interface ProyectosModel {
    idProyecto: number;
    idCliente: number | null;
    idClienteStr: string;
    nombre: string;
    clave: string;
    tipoProyectoId: number | null;
    tipoProyectoStr: string;
    idULider: number | null;
    idULiderStr: string;
    activo: boolean | null;
    idUCreo: number | null;
    fechaCreo: string | null;
    idUModifico: number | null;
    fechaModifico: string | null;
    claveVal: string;
    descripcion: string;
    semaforoID: number | null;
    avance: number | null;
    avanceReal: number | null;
    semaforo: string;
    horasEstimadasInicial: number | null;
    fechaInicioPlan: string | null;
    fechaFinPlan: string | null;
    ingresoPlan: number | null;
    fijarHoras: boolean | null;
    fijarFechas: boolean | null;
    fechaFinComprometida: string | null;
    fechaFinComprometidaAnt: string | null;
    costoPlan: number | null;
    horasFacturable: number;
    horasAsignadas: number;
    horasReales: number;
    horasCompromiso: number;
    desfase: number;
    horasPlan: number;
    horasProgreso: number;
    horasTerminadas: number;
    lider: string;
    avanceCompPorc: number;
    avanceRealPorc: number;
    desfaseProc: number;
    cPI: number;
    sPI: number;
    factorCalidad: number;
    metodologiaId: number | null;
    metodologiaIdStr: string;
    estatusIdStr: string;
    estatusId: number | null;
    visible: boolean;
    // actividades: ActividadesModel[];
    // usuarios: UsuarioModel[];
    idTipoRepositorio: number;
    organizacion: string;
    costoAplicado: number;
    mesMilestone: string;
    diaMilestone: string;
    milestone: string;
    milestones: number;
    mTerminados: number;
    mATiempo: number;
    mDesfasados: number;
    mAtrasados: number;
    costoPlaneado: number;
    costoActual: number;
    costoProyectado: number;
    costoHora: number;
    totalIngreso: number;
    facturado: number;
    cobrado: number;
    atrasado: number;
    saldo: number;
    idFlujoPagos: number;
    precioHora: number;
    rentabilidadPlan: number;
    rentabilidadActual: number;
    rentabilidadFacturado: number;
    rentabilidadProyectada: number;
    rentabilidadPlanImporte: number;
    rentabilidadActualImporte: number;
    rentabilidadProyectadaImporte: number;
    costoDisponible: number;
    costoActualPorc: number;
    fechaProyectada: string | null;
    estatus: string;
    pSP: boolean | null;
    horasPromedio: number | null;
    tecnologias: string;
    idPlantilla: number;
    porcIVA: number;
    puntosH: number;
    pTerminado: number;
    pPendiente: number;
    idWorkFlow: number;
}