//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadTipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActividadTipo()
        {
            this.ActividadTipoCampos = new HashSet<ActividadTipoCampos>();
            this.Actividad = new HashSet<Actividad>();
            this.WorkFlow = new HashSet<WorkFlow>();
        }
    
        public byte ActividadTipoId { get; set; }
        public string Nombre { get; set; }
        public Nullable<byte> Jerarquia { get; set; }
        public string Url { get; set; }
        public bool Activo { get; set; }
        public long IdUsuarioCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public string Plantilla { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadTipoCampos> ActividadTipoCampos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkFlow> WorkFlow { get; set; }
    }
}
