//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actividad()
        {
            this.ActividadArchivo = new HashSet<ActividadArchivo>();
            this.ActividadComentario = new HashSet<ActividadComentario>();
            this.ActividadDefecto = new HashSet<ActividadDefecto>();
            this.ActividadDependencia = new HashSet<ActividadDependencia>();
            this.ActividadDependencia1 = new HashSet<ActividadDependencia>();
            this.ActividadIssue = new HashSet<ActividadIssue>();
            this.ActividadListaRevision = new HashSet<ActividadListaRevision>();
            this.ActividadLog = new HashSet<ActividadLog>();
            this.ActividadRelacion = new HashSet<ActividadRelacion>();
            this.ActividadRelacion1 = new HashSet<ActividadRelacion>();
            this.ActividadRepositorio = new HashSet<ActividadRepositorio>();
            this.ActividadTamano = new HashSet<ActividadTamano>();
            this.ActividadTrabajo = new HashSet<ActividadTrabajo>();
            this.ActividadTracking = new HashSet<ActividadTracking>();
            this.ActividadValidaciones = new HashSet<ActividadValidaciones>();
            this.AuditoriaActividadMejora = new HashSet<AuditoriaActividadMejora>();
            this.CicloPrueba_CasosPrueba = new HashSet<CicloPrueba_CasosPrueba>();
            this.CicloPrueba_CasosPrueba1 = new HashSet<CicloPrueba_CasosPrueba>();
            this.FlujoPagoDet_Actividad = new HashSet<FlujoPagoDet_Actividad>();
            this.ProyectoIteracionComplete = new HashSet<ProyectoIteracionComplete>();
        }
    
        public long IdActividad { get; set; }
        public bool Critico { get; set; }
        public string BR { get; set; }
        public Nullable<long> IdUsuarioAsignado { get; set; }
        public Nullable<bool> Backlog { get; set; }
        public string Descripcion { get; set; }
        public string DocumentoRef { get; set; }
        public string Estatus { get; set; }
        public string EstatusCte { get; set; }
        public int Prioridad { get; set; }
        public Nullable<int> Planificada { get; set; }
        public string ComentariosFinales { get; set; }
        public Nullable<decimal> HorasFacturables { get; set; }
        public Nullable<decimal> HorasAsignadas { get; set; }
        public decimal HorasFinales { get; set; }
        public long IdProyecto { get; set; }
        public Nullable<long> IdIteracion { get; set; }
        public long TipoActividadId { get; set; }
        public Nullable<long> ClasificacionId { get; set; }
        public Nullable<long> IdUsuarioResponsable { get; set; }
        public Nullable<System.DateTime> FechaSolicitado { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<long> IdMotivoRechazo { get; set; }
        public string DescripcionRechazo { get; set; }
        public string EvidenciaRechazo { get; set; }
        public Nullable<long> IdActividadRef { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public Nullable<long> IdUMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<System.DateTime> FechaLiberacion { get; set; }
        public bool Retrabajo { get; set; }
        public Nullable<int> IdListaRevision { get; set; }
        public Nullable<byte> TipoId { get; set; }
        public Nullable<decimal> TiempoEjecucion { get; set; }
        public string CriterioAceptacion { get; set; }
        public Nullable<long> PrioridadId { get; set; }
        public Nullable<decimal> HorasPlan { get; set; }
        public string Fase { get; set; }
        public string Mes { get; set; }
        public string IdClaveExterna { get; set; }
        public Nullable<int> Puntos { get; set; }
        public Nullable<long> IdWorkflow { get; set; }
    
        public virtual ActividadTipo ActividadTipo { get; set; }
        public virtual ListaRevision ListaRevision { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual ProyectoIteracion ProyectoIteracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadArchivo> ActividadArchivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadComentario> ActividadComentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadDefecto> ActividadDefecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadDependencia> ActividadDependencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadDependencia> ActividadDependencia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadIssue> ActividadIssue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadListaRevision> ActividadListaRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadLog> ActividadLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadRelacion> ActividadRelacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadRelacion> ActividadRelacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadRepositorio> ActividadRepositorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadTamano> ActividadTamano { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadTrabajo> ActividadTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadTracking> ActividadTracking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadValidaciones> ActividadValidaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaActividadMejora> AuditoriaActividadMejora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CicloPrueba_CasosPrueba> CicloPrueba_CasosPrueba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CicloPrueba_CasosPrueba> CicloPrueba_CasosPrueba1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlujoPagoDet_Actividad> FlujoPagoDet_Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoIteracionComplete> ProyectoIteracionComplete { get; set; }
        public virtual WorkFlow WorkFlow { get; set; }
    }
}
