//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadArchivo
    {
        public long IdActividadArchivo { get; set; }
        public long IdActividad { get; set; }
        public string Nombre { get; set; }
        public string Extension { get; set; }
        public string Url { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Actividad Actividad { get; set; }
    }
}
