//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadTipoCampos
    {
        public int IdActividadTipoC { get; set; }
        public byte IdActividadTipo { get; set; }
        public string NombreCampo { get; set; }
        public string NombreCampoHTML { get; set; }
        public bool Requerido { get; set; }
        public bool Ver { get; set; }
    
        public virtual ActividadTipo ActividadTipo { get; set; }
    }
}
