//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadValidaciones
    {
        public long IdActividadVal { get; set; }
        public long IdActividad { get; set; }
        public long IdAutorizacion { get; set; }
        public string NombreAut { get; set; }
        public string Estatus { get; set; }
        public int Secuencia { get; set; }
        public Nullable<long> IdUAtendio { get; set; }
        public Nullable<System.DateTime> FechaAtendio { get; set; }
        public Nullable<long> MotivoRechazoId { get; set; }
        public string DescripcionRechazo { get; set; }
    
        public virtual Autorizacion Autorizacion { get; set; }
        public virtual Actividad Actividad { get; set; }
    }
}
