//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadTrabajo
    {
        public long IdActividadTrabajo { get; set; }
        public long IdActividad { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Tiempo { get; set; }
        public long IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Comentario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Actividad Actividad { get; set; }
    }
}
