//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadTracking
    {
        public long IdActividadTracking { get; set; }
        public long IdActividad { get; set; }
        public long IdFase { get; set; }
        public string Nombre { get; set; }
        public decimal Porcentaje { get; set; }
        public System.TimeSpan Trabajado { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<bool> Finalizado { get; set; }
    
        public virtual TipoActividadFase TipoActividadFase { get; set; }
        public virtual Actividad Actividad { get; set; }
    }
}
