//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadComentario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActividadComentario()
        {
            this.UsuarioComentario = new HashSet<UsuarioComentario>();
        }
    
        public long IdActividadComentario { get; set; }
        public long IdActividad { get; set; }
        public Nullable<long> IdActividadComentarioRel { get; set; }
        public string Comentario { get; set; }
        public long IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioComentario> UsuarioComentario { get; set; }
        public virtual Actividad Actividad { get; set; }
    }
}
