//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadRepositorio
    {
        public long IdActividadRepositorio { get; set; }
        public long IdActividad { get; set; }
        public long IdProyectoRepositorio { get; set; }
        public byte IdTipoLink { get; set; }
        public string IdLink { get; set; }
        public string Descripcion { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
    
        public virtual ProyectoRepositorio ProyectoRepositorio { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Actividad Actividad { get; set; }
    }
}
