//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadDefecto
    {
        public long IdActividadDefecto { get; set; }
        public long IdActividad { get; set; }
        public long TipoDefectoId { get; set; }
        public long IdFaseInyeccion { get; set; }
        public long IdFaseRemocion { get; set; }
        public System.DateTime FechaDefecto { get; set; }
        public System.TimeSpan Tiempo { get; set; }
        public string Descripcion { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
    
        public virtual CatalogoGeneral CatalogoGeneral { get; set; }
        public virtual TipoActividadFase TipoActividadFase { get; set; }
        public virtual TipoActividadFase TipoActividadFase1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Actividad Actividad { get; set; }
    }
}
