//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadTamano
    {
        public long IdActividadTamano { get; set; }
        public long IdActividad { get; set; }
        public long TipoParteId { get; set; }
        public string Descripcion { get; set; }
        public int EBase { get; set; }
        public int EEliminadas { get; set; }
        public int EModificadas { get; set; }
        public int EAgregadas { get; set; }
        public int ABase { get; set; }
        public int AEliminadas { get; set; }
        public int AModificadas { get; set; }
        public int AAgregadas { get; set; }
        public long IdUMod { get; set; }
        public System.DateTime FechaMod { get; set; }
    
        public virtual CatalogoGeneral CatalogoGeneral { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Actividad Actividad { get; set; }
    }
}
