//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriaActividadMejora
    {
        public int IdAuditoriaActividad { get; set; }
        public int IdAuditoria { get; set; }
        public long IdActividad { get; set; }
    
        public virtual Auditoria Auditoria { get; set; }
        public virtual Actividad Actividad { get; set; }
    }
}
