//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriaControlHallazgo
    {
        public long IdAuditoriaControlHallazgo { get; set; }
        public long IdAuditoriaControl { get; set; }
        public string Descripcion { get; set; }
        public byte Gravedad { get; set; }
        public bool Corregido { get; set; }
        public bool Activo { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public Nullable<long> IdUModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual AuditoriaControl AuditoriaControl { get; set; }
    }
}
