//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autorizacion()
        {
            this.ActividadValidaciones = new HashSet<ActividadValidaciones>();
            this.UsuarioAutorizacion = new HashSet<UsuarioAutorizacion>();
        }
    
        public long IdAutorizacion { get; set; }
        public string Nombre { get; set; }
        public int Tipo { get; set; }
        public bool Activo { get; set; }
        public int Secuencia { get; set; }
        public string EstatusAsigna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadValidaciones> ActividadValidaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioAutorizacion> UsuarioAutorizacion { get; set; }
    }
}
