//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDProductividad_DEVEntities : DbContext
    {
        public BDProductividad_DEVEntities(String Conexion)
            : base(Conexion)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatalogoGeneral> CatalogoGeneral { get; set; }
        public virtual DbSet<Configuracion> Configuracion { get; set; }
        public virtual DbSet<Graficas> Graficas { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<NivelesSemanas> NivelesSemanas { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<TipoUsuarioPermisos> TipoUsuarioPermisos { get; set; }
        public virtual DbSet<UsuarioAutorizacion> UsuarioAutorizacion { get; set; }
        public virtual DbSet<UsuarioPermisos> UsuarioPermisos { get; set; }
        public virtual DbSet<ActividadLog> ActividadLog { get; set; }
        public virtual DbSet<ActividadValidaciones> ActividadValidaciones { get; set; }
        public virtual DbSet<UsuarioIncidencias> UsuarioIncidencias { get; set; }
        public virtual DbSet<CalendarioTrabajo> CalendarioTrabajo { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<HistoricoCompensacion> HistoricoCompensacion { get; set; }
        public virtual DbSet<Autorizacion> Autorizacion { get; set; }
        public virtual DbSet<TipoActividadFase> TipoActividadFase { get; set; }
        public virtual DbSet<ActividadTracking> ActividadTracking { get; set; }
        public virtual DbSet<ActividadArchivo> ActividadArchivo { get; set; }
        public virtual DbSet<ActividadDefecto> ActividadDefecto { get; set; }
        public virtual DbSet<DiasFestivos> DiasFestivos { get; set; }
        public virtual DbSet<Niveles> Niveles { get; set; }
        public virtual DbSet<ActividadDependencia> ActividadDependencia { get; set; }
        public virtual DbSet<ListaControl> ListaControl { get; set; }
        public virtual DbSet<ListaControlDetalle> ListaControlDetalle { get; set; }
        public virtual DbSet<ProyectoListaControl> ProyectoListaControl { get; set; }
        public virtual DbSet<ProyectoListaControlDetalle> ProyectoListaControlDetalle { get; set; }
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<AuditoriaControl> AuditoriaControl { get; set; }
        public virtual DbSet<AuditoriaControlHallazgo> AuditoriaControlHallazgo { get; set; }
        public virtual DbSet<ActividadTamano> ActividadTamano { get; set; }
        public virtual DbSet<ProyectoIssueComentario> ProyectoIssueComentario { get; set; }
        public virtual DbSet<ProyectoIssue> ProyectoIssue { get; set; }
        public virtual DbSet<RiesgoEvaluacion> RiesgoEvaluacion { get; set; }
        public virtual DbSet<RiesgoImpacto> RiesgoImpacto { get; set; }
        public virtual DbSet<RiesgoProbabilidad> RiesgoProbabilidad { get; set; }
        public virtual DbSet<Riesgo> Riesgo { get; set; }
        public virtual DbSet<ProyectoRiesgoComentario> ProyectoRiesgoComentario { get; set; }
        public virtual DbSet<AuditoriaActividadMejora> AuditoriaActividadMejora { get; set; }
        public virtual DbSet<ListaControlCorreo> ListaControlCorreo { get; set; }
        public virtual DbSet<ProyectoRiesgo> ProyectoRiesgo { get; set; }
        public virtual DbSet<ProyectoRiesgoEstrategia> ProyectoRiesgoEstrategia { get; set; }
        public virtual DbSet<ListaRevision> ListaRevision { get; set; }
        public virtual DbSet<ListaRevisionDetalle> ListaRevisionDetalle { get; set; }
        public virtual DbSet<ActividadListaRevision> ActividadListaRevision { get; set; }
        public virtual DbSet<ActividadListaRevisionHallazgo> ActividadListaRevisionHallazgo { get; set; }
        public virtual DbSet<TipoRepositorio> TipoRepositorio { get; set; }
        public virtual DbSet<ProyectoRepositorio> ProyectoRepositorio { get; set; }
        public virtual DbSet<ActividadRepositorio> ActividadRepositorio { get; set; }
        public virtual DbSet<UsuarioCosto> UsuarioCosto { get; set; }
        public virtual DbSet<ProyectoCD> ProyectoCD { get; set; }
        public virtual DbSet<ProyectoCI> ProyectoCI { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<ActividadTrabajo> ActividadTrabajo { get; set; }
        public virtual DbSet<ActividadIssue> ActividadIssue { get; set; }
        public virtual DbSet<LogEventos> LogEventos { get; set; }
        public virtual DbSet<UsuarioAsistencia> UsuarioAsistencia { get; set; }
        public virtual DbSet<NivelesHoras> NivelesHoras { get; set; }
        public virtual DbSet<UsuarioCostoMensual> UsuarioCostoMensual { get; set; }
        public virtual DbSet<UsuarioCostoDistribucion> UsuarioCostoDistribucion { get; set; }
        public virtual DbSet<UsuarioFeels> UsuarioFeels { get; set; }
        public virtual DbSet<ProyectoUsuario> ProyectoUsuario { get; set; }
        public virtual DbSet<Pregunta> Pregunta { get; set; }
        public virtual DbSet<PreguntaRespuesta> PreguntaRespuesta { get; set; }
        public virtual DbSet<ActividadTipoCampos> ActividadTipoCampos { get; set; }
        public virtual DbSet<ActividadRelacion> ActividadRelacion { get; set; }
        public virtual DbSet<CicloPrueba> CicloPrueba { get; set; }
        public virtual DbSet<CicloPrueba_CasosPrueba> CicloPrueba_CasosPrueba { get; set; }
        public virtual DbSet<FlujoPagoDet_Actividad> FlujoPagoDet_Actividad { get; set; }
        public virtual DbSet<FlujoPagoDetalle> FlujoPagoDetalle { get; set; }
        public virtual DbSet<FlujoPago> FlujoPago { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<ActividadTipo> ActividadTipo { get; set; }
        public virtual DbSet<Query> Query { get; set; }
        public virtual DbSet<QueryShare> QueryShare { get; set; }
        public virtual DbSet<ProyectoDocumentos> ProyectoDocumentos { get; set; }
        public virtual DbSet<Plantilla> Plantilla { get; set; }
        public virtual DbSet<ActividadComentario> ActividadComentario { get; set; }
        public virtual DbSet<UsuarioComentario> UsuarioComentario { get; set; }
        public virtual DbSet<ProyectoIteracionShare> ProyectoIteracionShare { get; set; }
        public virtual DbSet<ProyectoIteracionComplete> ProyectoIteracionComplete { get; set; }
        public virtual DbSet<ProyectoIteracion> ProyectoIteracion { get; set; }
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<WorkFlow> WorkFlow { get; set; }
        public virtual DbSet<WorkFlowConfig> WorkFlowConfig { get; set; }
        public virtual DbSet<WorkFlowConfigDetail> WorkFlowConfigDetail { get; set; }
        public virtual DbSet<Views> Views { get; set; }
        public virtual DbSet<WorkSpace> WorkSpace { get; set; }
        public virtual DbSet<WorkSpaceShare> WorkSpaceShare { get; set; }
        public virtual DbSet<WorkSpaceTabs> WorkSpaceTabs { get; set; }
        public virtual DbSet<Widget> Widget { get; set; }
        public virtual DbSet<WorkSpaceTabsFile> WorkSpaceTabsFile { get; set; }
    }
}
