//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CicloPrueba_CasosPrueba
    {
        public long IdCicloCaso { get; set; }
        public long IdCicloP { get; set; }
        public long IdActividadCaso { get; set; }
        public Nullable<long> IdActividadEjecucion { get; set; }
        public string EstatusP { get; set; }
        public Nullable<System.DateTime> FechaEjecucion { get; set; }
        public string Comentarios { get; set; }
        public string Evidencias { get; set; }
    
        public virtual CicloPrueba CicloPrueba { get; set; }
        public virtual Actividad Actividad { get; set; }
        public virtual Actividad Actividad1 { get; set; }
    }
}
