//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaOrganizacion
    {
        public long IdCuentaOrg { get; set; }
        public long IdCuenta { get; set; }
        public long IdOrganizacion { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Organizacion Organizacion { get; set; }
    }
}
