//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlujoPagoDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlujoPagoDetalle()
        {
            this.FlujoPagoDet_Actividad = new HashSet<FlujoPagoDet_Actividad>();
        }
    
        public long IdFlujoPagoDet { get; set; }
        public long IdFlujoPago { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> Horas { get; set; }
        public Nullable<decimal> Amortizadas { get; set; }
        public Nullable<decimal> Procentaje { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> FechaDevOriginal { get; set; }
        public Nullable<System.DateTime> FechaDev { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<System.DateTime> FechaProgramadaPago { get; set; }
        public Nullable<System.DateTime> FechaPagoReal { get; set; }
        public bool Facturable { get; set; }
        public bool Facturada { get; set; }
        public bool Pagada { get; set; }
        public string Comentarios { get; set; }
        public string Factura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlujoPagoDet_Actividad> FlujoPagoDet_Actividad { get; set; }
        public virtual FlujoPago FlujoPago { get; set; }
    }
}
