//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlujoPagoDet_Actividad
    {
        public long IdFlujoPagoDetAct { get; set; }
        public long IdFlujoPagoDet { get; set; }
        public long IdActividad { get; set; }
    
        public virtual FlujoPagoDetalle FlujoPagoDetalle { get; set; }
        public virtual Actividad Actividad { get; set; }
    }
}
