//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlujoPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlujoPago()
        {
            this.FlujoPagoDetalle = new HashSet<FlujoPagoDetalle>();
        }
    
        public long IdFlujoPago { get; set; }
        public long IdProyecto { get; set; }
        public decimal PrecioHora { get; set; }
        public decimal HorasTotales { get; set; }
        public decimal PorcIVA { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public long IdUCreo { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<long> IdUMod { get; set; }
        public bool Activo { get; set; }
        public decimal HorasAmortizar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlujoPagoDetalle> FlujoPagoDetalle { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
