//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graficas
    {
        public int IdGrafica { get; set; }
        public string Nombre { get; set; }
        public string Ejecucion { get; set; }
        public string TipoGrafica { get; set; }
        public bool Activo { get; set; }
    }
}
