//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoCompensacion
    {
        public long IdHisorico { get; set; }
        public int IdAnio { get; set; }
        public int IdMes { get; set; }
        public System.DateTime FechaCorte { get; set; }
        public long IdUsuario { get; set; }
        public string Recurso { get; set; }
        public string Nivel { get; set; }
        public decimal EstandarMes { get; set; }
        public decimal HorasSolicitadas { get; set; }
        public decimal HorasLiberadas { get; set; }
        public decimal BonoCumplimiento { get; set; }
        public decimal HorasAdicionales { get; set; }
        public decimal BonoHoras { get; set; }
        public decimal Productividad { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
    }
}
