//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaControlCorreo
    {
        public int IdListaControlCorreo { get; set; }
        public int IdListaControl { get; set; }
        public string correo { get; set; }
    
        public virtual ListaControl ListaControl { get; set; }
    }
}
