//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaRevision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListaRevision()
        {
            this.ListaRevisionDetalle = new HashSet<ListaRevisionDetalle>();
            this.Actividad = new HashSet<Actividad>();
        }
    
        public int IdListaRevision { get; set; }
        public Nullable<long> IdProyecto { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> CatalogoFaseId { get; set; }
        public Nullable<long> CatalogoClasificacionId { get; set; }
        public bool Activo { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public Nullable<long> IdUModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual CatalogoGeneral CatalogoGeneral { get; set; }
        public virtual CatalogoGeneral CatalogoGeneral1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaRevisionDetalle> ListaRevisionDetalle { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad { get; set; }
    }
}
