//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NivelesSemanas
    {
        public long IdNivelEstab { get; set; }
        public long IdNivel { get; set; }
        public int Semana { get; set; }
        public decimal Horas { get; set; }
    
        public virtual Niveles Niveles { get; set; }
    }
}
