//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organizacion()
        {
            this.Cuenta = new HashSet<Cuenta>();
            this.CuentaOrganizacion = new HashSet<CuentaOrganizacion>();
        }
    
        public long IdOrganizacion { get; set; }
        public string Nombre { get; set; }
        public string RFC { get; set; }
        public int Licencias { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string Servidor { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string BD { get; set; }
        public bool Activo { get; set; }
        public Nullable<bool> ActiveDirectoryAuth { get; set; }
        public string KeySecret { get; set; }
        public Nullable<bool> Api { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta> Cuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaOrganizacion> CuentaOrganizacion { get; set; }
    }
}
