//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantilla
    {
        public long IdPlantilla { get; set; }
        public long CategoriaId { get; set; }
        public string Titulo { get; set; }
        public string Nombre { get; set; }
        public string Descripción { get; set; }
        public string Contenido { get; set; }
        public long Activo { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public long IdUMod { get; set; }
        public System.DateTime FechaMod { get; set; }
    
        public virtual CatalogoGeneral CatalogoGeneral { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
