//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntaRespuesta
    {
        public long IdPreguntaRespuesta { get; set; }
        public long IdPregunta { get; set; }
        public long IdUsuario { get; set; }
        public string Respuesta { get; set; }
        public System.DateTime FechaRespuesta { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
