//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProyectoIssue()
        {
            this.ProyectoIssueComentario = new HashSet<ProyectoIssueComentario>();
            this.ActividadIssue = new HashSet<ActividadIssue>();
        }
    
        public long IdIssue { get; set; }
        public int IdIssueProyecto { get; set; }
        public Nullable<long> IdProyecto { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaDeteccion { get; set; }
        public Nullable<System.DateTime> FechaCompromiso { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<long> CatalogoPrioridadId { get; set; }
        public Nullable<long> CatalogoEstatusId { get; set; }
        public bool Bloqueante { get; set; }
        public Nullable<long> IdUResponsable { get; set; }
        public string ResponsableExterno { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public Nullable<long> IdUModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual CatalogoGeneral CatalogoGeneral { get; set; }
        public virtual CatalogoGeneral CatalogoGeneral1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoIssueComentario> ProyectoIssueComentario { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadIssue> ActividadIssue { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
