//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoRiesgoEstrategia
    {
        public int IdProyectoRiesgoEstrategia { get; set; }
        public int IdProyectoRiesgo { get; set; }
        public long CatalogoEstrategiaId { get; set; }
        public string PlanMitigacion { get; set; }
        public long IdUResponsable { get; set; }
        public string DisparadorPlan { get; set; }
        public Nullable<System.DateTime> FechaIdentificacion { get; set; }
        public bool Realizada { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
    
        public virtual CatalogoGeneral CatalogoGeneral { get; set; }
        public virtual ProyectoRiesgo ProyectoRiesgo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
