//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto()
        {
            this.CicloPrueba = new HashSet<CicloPrueba>();
            this.FlujoPago = new HashSet<FlujoPago>();
            this.ListaRevision = new HashSet<ListaRevision>();
            this.ProyectoListaControl = new HashSet<ProyectoListaControl>();
            this.ProyectoCD = new HashSet<ProyectoCD>();
            this.ProyectoCI = new HashSet<ProyectoCI>();
            this.ProyectoIssue = new HashSet<ProyectoIssue>();
            this.ProyectoRepositorio = new HashSet<ProyectoRepositorio>();
            this.ProyectoRiesgo = new HashSet<ProyectoRiesgo>();
            this.ProyectoUsuario = new HashSet<ProyectoUsuario>();
            this.UsuarioCostoDistribucion = new HashSet<UsuarioCostoDistribucion>();
            this.ProyectoDocumentos = new HashSet<ProyectoDocumentos>();
            this.ProyectoIteracion = new HashSet<ProyectoIteracion>();
            this.Actividad = new HashSet<Actividad>();
            this.WorkFlow = new HashSet<WorkFlow>();
        }
    
        public long IdProyecto { get; set; }
        public Nullable<long> IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Clave { get; set; }
        public Nullable<long> TipoProyectoId { get; set; }
        public Nullable<long> IdULider { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<long> IdUCreo { get; set; }
        public Nullable<System.DateTime> FechaCreo { get; set; }
        public Nullable<long> IdUModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> SemaforoID { get; set; }
        public Nullable<decimal> Avance { get; set; }
        public Nullable<decimal> AvanceReal { get; set; }
        public Nullable<bool> FijarHoras { get; set; }
        public Nullable<decimal> HorasEstimadasInicial { get; set; }
        public Nullable<bool> FijarFechas { get; set; }
        public Nullable<System.DateTime> FechaInicioPlan { get; set; }
        public Nullable<System.DateTime> FechaFinPlan { get; set; }
        public Nullable<System.DateTime> FechaFinComprometida { get; set; }
        public Nullable<System.DateTime> FechaFinComprometidaAnt { get; set; }
        public Nullable<decimal> IngresoPlan { get; set; }
        public Nullable<decimal> CostoPlan { get; set; }
        public Nullable<long> MetodologiaId { get; set; }
        public Nullable<long> EstatusId { get; set; }
        public Nullable<bool> PSP { get; set; }
        public Nullable<decimal> HorasPromedio { get; set; }
        public string Tecnologias { get; set; }
    
        public virtual CatalogoGeneral CatalogoGeneral { get; set; }
        public virtual CatalogoGeneral CatalogoGeneral1 { get; set; }
        public virtual CatalogoGeneral CatalogoGeneral2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CicloPrueba> CicloPrueba { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlujoPago> FlujoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaRevision> ListaRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoListaControl> ProyectoListaControl { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoCD> ProyectoCD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoCI> ProyectoCI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoIssue> ProyectoIssue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoRepositorio> ProyectoRepositorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoRiesgo> ProyectoRiesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoUsuario> ProyectoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioCostoDistribucion> UsuarioCostoDistribucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoDocumentos> ProyectoDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoIteracion> ProyectoIteracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkFlow> WorkFlow { get; set; }
    }
}
