//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoRepositorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProyectoRepositorio()
        {
            this.ActividadRepositorio = new HashSet<ActividadRepositorio>();
        }
    
        public long IdProyectoRepositorio { get; set; }
        public long IdProyecto { get; set; }
        public byte IdTipoRepositorio { get; set; }
        public string Nombre { get; set; }
        public string Organizacion { get; set; }
        public string Proyecto { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadRepositorio> ActividadRepositorio { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Proyecto Proyecto1 { get; set; }
    }
}
