//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoRiesgo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProyectoRiesgo()
        {
            this.ProyectoRiesgoComentario = new HashSet<ProyectoRiesgoComentario>();
            this.ProyectoRiesgoEstrategia = new HashSet<ProyectoRiesgoEstrategia>();
        }
    
        public int IdProyectoRiesgo { get; set; }
        public Nullable<int> IdRiesgo { get; set; }
        public long IdProyecto { get; set; }
        public short ConsecutivoProyecto { get; set; }
        public System.DateTime FechaIdentificacion { get; set; }
        public long CatalogoCategoriaId { get; set; }
        public long CatalogoFuenteId { get; set; }
        public string DescripcionRiesgo { get; set; }
        public string DescripcionEfecto { get; set; }
        public string Causas { get; set; }
        public string EventoMaterializacion { get; set; }
        public byte IdRiesgoImpacto { get; set; }
        public byte IdRiesgoProbabilidad { get; set; }
        public bool Activo { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public Nullable<long> CatalogoEstrategiaId { get; set; }
        public string PlanMitigacion { get; set; }
        public Nullable<long> IdUResponsable { get; set; }
        public string DisparadorPlan { get; set; }
        public string Descripcion { get; set; }
    
        public virtual CatalogoGeneral CatalogoGeneral { get; set; }
        public virtual CatalogoGeneral CatalogoGeneral1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoRiesgoComentario> ProyectoRiesgoComentario { get; set; }
        public virtual Riesgo Riesgo { get; set; }
        public virtual RiesgoImpacto RiesgoImpacto { get; set; }
        public virtual RiesgoProbabilidad RiesgoProbabilidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoRiesgoEstrategia> ProyectoRiesgoEstrategia { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual CatalogoGeneral CatalogoGeneral11 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
