//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoRiesgoComentario
    {
        public long IdProyectoRiesgoComentario { get; set; }
        public int IdProyectoRiesgo { get; set; }
        public string Comentario { get; set; }
        public bool Autogenerado { get; set; }
        public bool Activo { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public Nullable<long> IdUElimino { get; set; }
        public Nullable<System.DateTime> FechaElimino { get; set; }
    
        public virtual ProyectoRiesgo ProyectoRiesgo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
