//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoDocumentos
    {
        public long IdProDoc { get; set; }
        public long IdProyecto { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<System.DateTime> FechaCreo { get; set; }
        public Nullable<long> IdUCreo { get; set; }
        public Nullable<System.DateTime> FechaElimino { get; set; }
        public Nullable<long> IdUElimino { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<long> TipoDocumentoId { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
