//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoCD
    {
        public long IdProyectoCD { get; set; }
        public long IdProyecto { get; set; }
        public Nullable<long> IdRecurso { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> TipoActividadId { get; set; }
        public decimal CostoMensual { get; set; }
        public decimal CostoPeriodo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int Dias { get; set; }
        public decimal PorcDedicado { get; set; }
        public decimal HorasInvertidas { get; set; }
        public bool Aplicado { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public Nullable<long> IdUMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
    
        public virtual CatalogoGeneral CatalogoGeneral { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
