//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoListaControlDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProyectoListaControlDetalle()
        {
            this.AuditoriaControl = new HashSet<AuditoriaControl>();
        }
    
        public long IdProyectoListaControlDetalle { get; set; }
        public Nullable<long> IdListaControlDetalle { get; set; }
        public int IdProyectoListaControl { get; set; }
        public string Control { get; set; }
        public bool Activo { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public Nullable<long> IdUModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual ListaControlDetalle ListaControlDetalle { get; set; }
        public virtual ProyectoListaControl ProyectoListaControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaControl> AuditoriaControl { get; set; }
    }
}
