//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueryShare
    {
        public long IdQueryU { get; set; }
        public long IdQuery { get; set; }
        public long IdUsuario { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
    
        public virtual Query Query { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
