//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiesgoProbabilidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiesgoProbabilidad()
        {
            this.Riesgo = new HashSet<Riesgo>();
            this.ProyectoRiesgo = new HashSet<ProyectoRiesgo>();
        }
    
        public byte IdRiesoProbabilidad { get; set; }
        public byte Valor { get; set; }
        public string Cualitativo { get; set; }
        public string Cuantitativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Riesgo> Riesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoRiesgo> ProyectoRiesgo { get; set; }
    }
}
