//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Riesgo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Riesgo()
        {
            this.ProyectoRiesgo = new HashSet<ProyectoRiesgo>();
        }
    
        public int IdRiesgo { get; set; }
        public System.DateTime FechaIdentificacion { get; set; }
        public long CatalogoCategoriaId { get; set; }
        public long CatalogoFuenteId { get; set; }
        public string DescripcionRiesgo { get; set; }
        public string DescripcionEfecto { get; set; }
        public string Causas { get; set; }
        public string EventoMaterializacion { get; set; }
        public byte IdRiesgoImpacto { get; set; }
        public byte IdRiesgoProbabilidad { get; set; }
        public bool Activo { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
    
        public virtual CatalogoGeneral CatalogoGeneral { get; set; }
        public virtual CatalogoGeneral CatalogoGeneral1 { get; set; }
        public virtual RiesgoImpacto RiesgoImpacto { get; set; }
        public virtual RiesgoProbabilidad RiesgoProbabilidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoRiesgo> ProyectoRiesgo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
