//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUsuarioPermisos
    {
        public long IdPermisoTU { get; set; }
        public int IdMenu { get; set; }
        public int IdTipoUsuario { get; set; }
        public bool Ver { get; set; }
        public bool Guardar { get; set; }
        public bool Modificar { get; set; }
        public bool Imprimir { get; set; }
        public bool Eliminar { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
