//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoActividadFase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoActividadFase()
        {
            this.ActividadTracking = new HashSet<ActividadTracking>();
            this.ActividadDefecto = new HashSet<ActividadDefecto>();
            this.ActividadDefecto1 = new HashSet<ActividadDefecto>();
        }
    
        public long IdFase { get; set; }
        public long TipoActividadId { get; set; }
        public string Nombre { get; set; }
        public decimal Porcentaje { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual CatalogoGeneral CatalogoGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadTracking> ActividadTracking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadDefecto> ActividadDefecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadDefecto> ActividadDefecto1 { get; set; }
    }
}
