//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioFeels
    {
        public long IdFeels { get; set; }
        public long IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Resultado { get; set; }
        public string Comentarios { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
