//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.ActividadArchivo = new HashSet<ActividadArchivo>();
            this.ActividadDefecto = new HashSet<ActividadDefecto>();
            this.ActividadListaRevision = new HashSet<ActividadListaRevision>();
            this.ActividadListaRevision1 = new HashSet<ActividadListaRevision>();
            this.ActividadListaRevisionHallazgo = new HashSet<ActividadListaRevisionHallazgo>();
            this.ActividadListaRevisionHallazgo1 = new HashSet<ActividadListaRevisionHallazgo>();
            this.ActividadLog = new HashSet<ActividadLog>();
            this.ActividadRepositorio = new HashSet<ActividadRepositorio>();
            this.ActividadTamano = new HashSet<ActividadTamano>();
            this.AuditoriaControl = new HashSet<AuditoriaControl>();
            this.ListaRevision = new HashSet<ListaRevision>();
            this.ListaRevision1 = new HashSet<ListaRevision>();
            this.ListaRevisionDetalle = new HashSet<ListaRevisionDetalle>();
            this.ListaRevisionDetalle1 = new HashSet<ListaRevisionDetalle>();
            this.ProyectoCD = new HashSet<ProyectoCD>();
            this.ProyectoCD1 = new HashSet<ProyectoCD>();
            this.ProyectoCD2 = new HashSet<ProyectoCD>();
            this.ProyectoCI = new HashSet<ProyectoCI>();
            this.ProyectoCI1 = new HashSet<ProyectoCI>();
            this.ProyectoIssue = new HashSet<ProyectoIssue>();
            this.ProyectoIssue1 = new HashSet<ProyectoIssue>();
            this.ProyectoIssue2 = new HashSet<ProyectoIssue>();
            this.ProyectoIssueComentario = new HashSet<ProyectoIssueComentario>();
            this.ProyectoIssueComentario1 = new HashSet<ProyectoIssueComentario>();
            this.ProyectoRepositorio = new HashSet<ProyectoRepositorio>();
            this.ProyectoRiesgo = new HashSet<ProyectoRiesgo>();
            this.ProyectoRiesgoComentario = new HashSet<ProyectoRiesgoComentario>();
            this.ProyectoRiesgoComentario1 = new HashSet<ProyectoRiesgoComentario>();
            this.ProyectoRiesgoEstrategia = new HashSet<ProyectoRiesgoEstrategia>();
            this.ProyectoRiesgoEstrategia1 = new HashSet<ProyectoRiesgoEstrategia>();
            this.Riesgo = new HashSet<Riesgo>();
            this.Usuario1 = new HashSet<Usuario>();
            this.UsuarioAutorizacion = new HashSet<UsuarioAutorizacion>();
            this.UsuarioIncidencias = new HashSet<UsuarioIncidencias>();
            this.UsuarioIncidencias1 = new HashSet<UsuarioIncidencias>();
            this.UsuarioPermisos = new HashSet<UsuarioPermisos>();
            this.ActividadTrabajo = new HashSet<ActividadTrabajo>();
            this.ProyectoRiesgo1 = new HashSet<ProyectoRiesgo>();
            this.LogEventos = new HashSet<LogEventos>();
            this.UsuarioAsistencia = new HashSet<UsuarioAsistencia>();
            this.NivelesHoras = new HashSet<NivelesHoras>();
            this.NivelesHoras1 = new HashSet<NivelesHoras>();
            this.UsuarioCostoDistribucion = new HashSet<UsuarioCostoDistribucion>();
            this.UsuarioFeels = new HashSet<UsuarioFeels>();
            this.ProyectoUsuario = new HashSet<ProyectoUsuario>();
            this.PreguntaRespuesta = new HashSet<PreguntaRespuesta>();
            this.CicloPrueba = new HashSet<CicloPrueba>();
            this.Proyecto = new HashSet<Proyecto>();
            this.Proyecto1 = new HashSet<Proyecto>();
            this.Proyecto2 = new HashSet<Proyecto>();
            this.QueryShare = new HashSet<QueryShare>();
            this.QueryShare1 = new HashSet<QueryShare>();
            this.ProyectoDocumentos = new HashSet<ProyectoDocumentos>();
            this.ProyectoDocumentos1 = new HashSet<ProyectoDocumentos>();
            this.Plantilla = new HashSet<Plantilla>();
            this.Plantilla1 = new HashSet<Plantilla>();
            this.ActividadComentario = new HashSet<ActividadComentario>();
            this.UsuarioComentario = new HashSet<UsuarioComentario>();
            this.ProyectoIteracionShare = new HashSet<ProyectoIteracionShare>();
            this.ProyectoIteracionShare1 = new HashSet<ProyectoIteracionShare>();
            this.ProyectoIteracionComplete = new HashSet<ProyectoIteracionComplete>();
            this.ProyectoIteracion = new HashSet<ProyectoIteracion>();
            this.WorkSpace = new HashSet<WorkSpace>();
            this.WorkSpace1 = new HashSet<WorkSpace>();
            this.WorkSpaceShare = new HashSet<WorkSpaceShare>();
            this.WorkSpaceShare1 = new HashSet<WorkSpaceShare>();
            this.WorkSpaceTabs = new HashSet<WorkSpaceTabs>();
            this.WorkSpaceTabsFile = new HashSet<WorkSpaceTabsFile>();
        }
    
        public long IdUsuario { get; set; }
        public string NumEmpleado { get; set; }
        public string Nombre { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaCambioNivel { get; set; }
        public Nullable<long> IdNivel { get; set; }
        public int IdTipoUsuario { get; set; }
        public Nullable<long> IdUGerente { get; set; }
        public long DepartamentoId { get; set; }
        public Nullable<int> IntentosBloqueo { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public bool Captura { get; set; }
        public bool Activo { get; set; }
        public bool Bloqueado { get; set; }
        public string Contrasena { get; set; }
        public System.DateTime FechaContrasena { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public Nullable<long> IdUMod { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadArchivo> ActividadArchivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadDefecto> ActividadDefecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadListaRevision> ActividadListaRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadListaRevision> ActividadListaRevision1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadListaRevisionHallazgo> ActividadListaRevisionHallazgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadListaRevisionHallazgo> ActividadListaRevisionHallazgo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadLog> ActividadLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadRepositorio> ActividadRepositorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadTamano> ActividadTamano { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaControl> AuditoriaControl { get; set; }
        public virtual CatalogoGeneral CatalogoGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaRevision> ListaRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaRevision> ListaRevision1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaRevisionDetalle> ListaRevisionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaRevisionDetalle> ListaRevisionDetalle1 { get; set; }
        public virtual Niveles Niveles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoCD> ProyectoCD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoCD> ProyectoCD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoCD> ProyectoCD2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoCI> ProyectoCI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoCI> ProyectoCI1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoIssue> ProyectoIssue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoIssue> ProyectoIssue1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoIssue> ProyectoIssue2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoIssueComentario> ProyectoIssueComentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoIssueComentario> ProyectoIssueComentario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoRepositorio> ProyectoRepositorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoRiesgo> ProyectoRiesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoRiesgoComentario> ProyectoRiesgoComentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoRiesgoComentario> ProyectoRiesgoComentario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoRiesgoEstrategia> ProyectoRiesgoEstrategia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoRiesgoEstrategia> ProyectoRiesgoEstrategia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Riesgo> Riesgo { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioAutorizacion> UsuarioAutorizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioIncidencias> UsuarioIncidencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioIncidencias> UsuarioIncidencias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioPermisos> UsuarioPermisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadTrabajo> ActividadTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoRiesgo> ProyectoRiesgo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogEventos> LogEventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioAsistencia> UsuarioAsistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NivelesHoras> NivelesHoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NivelesHoras> NivelesHoras1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioCostoDistribucion> UsuarioCostoDistribucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioFeels> UsuarioFeels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoUsuario> ProyectoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreguntaRespuesta> PreguntaRespuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CicloPrueba> CicloPrueba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyecto> Proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyecto> Proyecto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyecto> Proyecto2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueryShare> QueryShare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueryShare> QueryShare1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoDocumentos> ProyectoDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoDocumentos> ProyectoDocumentos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantilla> Plantilla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantilla> Plantilla1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadComentario> ActividadComentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioComentario> UsuarioComentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoIteracionShare> ProyectoIteracionShare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoIteracionShare> ProyectoIteracionShare1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoIteracionComplete> ProyectoIteracionComplete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoIteracion> ProyectoIteracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSpace> WorkSpace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSpace> WorkSpace1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSpaceShare> WorkSpaceShare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSpaceShare> WorkSpaceShare1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSpaceTabs> WorkSpaceTabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSpaceTabsFile> WorkSpaceTabsFile { get; set; }
    }
}
