//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkFlow()
        {
            this.Actividad = new HashSet<Actividad>();
        }
    
        public long IdWorkFlow { get; set; }
        public long IdProyecto { get; set; }
        public byte IdActividadTipo { get; set; }
        public string Nombre { get; set; }
        public int Orden { get; set; }
        public string Color { get; set; }
        public string ColorTexto { get; set; }
        public string EstatusR { get; set; }
        public int WIP { get; set; }
        public Nullable<bool> Notifica { get; set; }
        public Nullable<int> TipoNotificacion { get; set; }
        public Nullable<bool> Editable { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public Nullable<long> IduMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad { get; set; }
        public virtual ActividadTipo ActividadTipo { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
