//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSpaceTabsFile
    {
        public long IdWorkSpaceTabFile { get; set; }
        public long IdWorkSpaceTab { get; set; }
        public string BlobId { get; set; }
        public string URL { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Tamano { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual WorkSpaceTabs WorkSpaceTabs { get; set; }
    }
}
