//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowConfigDetail
    {
        public long IdWorkFlowCD { get; set; }
        public long IdWorkFlowC { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
        public string ColorTexto { get; set; }
        public string EstatusR { get; set; }
        public int WIP { get; set; }
        public Nullable<bool> Notifica { get; set; }
        public Nullable<int> TipoNotificacion { get; set; }
        public Nullable<bool> Editable { get; set; }
        public int Orden { get; set; }
    }
}
