//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSpaceTabs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkSpaceTabs()
        {
            this.WorkSpaceTabsFile = new HashSet<WorkSpaceTabsFile>();
        }
    
        public long IdWorkSpaceTab { get; set; }
        public long IdWorkSpace { get; set; }
        public string Nombre { get; set; }
        public string Parametros { get; set; }
        public string Filtros { get; set; }
        public string Columnas { get; set; }
        public string Agrupador { get; set; }
        public string Tipo { get; set; }
        public int Orden { get; set; }
        public string Widgets { get; set; }
        public string LayoutConfig { get; set; }
        public Nullable<int> NextId { get; set; }
        public bool Fijo { get; set; }
        public long IdUCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public Nullable<long> IdUMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual WorkSpace WorkSpace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSpaceTabsFile> WorkSpaceTabsFile { get; set; }
    }
}
