using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaDatos.Models
{
    public class MimeType
    {
        public const string ACC = "audio/aac";
        public const string ABW = "application/x-abiword";
        public const string ARC = "application/x-freearc";
        public const string AVI = "video/x-msvideo";
        public const string AZW = "application/vnd.amazon.ebook";
        public const string BIN = "application/octet-stream";
        public const string BMP = "image/bmp";
        public const string BZ = "application/x-bzip";
        public const string BZ2 = "application/x-bzip2";
        public const string CSH = "application/x-csh";
        public const string CSS = "text/css";
        public const string CSV = "text/csv";
        public const string DOC = "application/msword";
        public const string DOCX = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
        public const string EOT = "application/vnd.ms-fontobject";
        public const string EPUB = "application/epub+zip";
        public const string GZ = "application/gzip";
        public const string GIF = "image/gif";
        public const string HTM = "text/html";
        public const string HTML = "text/html";
        public const string ICO = "image/vnd.microsoft.icon";
        public const string ICS = "text/calendar";
        public const string JAR = "application/java-archive";
        public const string JPG = "image/jpeg";
        public const string JPEG = "image/jpeg";
        public const string JS = "text/javascript";
        public const string JSON = "application/json";
        public const string JSONLD = "application/ld+json";
        public const string MJS = "text/javascript";
        public const string MP3 = "audio/mpeg";
        public const string MPEG = "video/mpeg";
        public const string MPKE = "application/vnd.apple.installer+xml";
        public const string ODP = "application/vnd.oasis.opendocument.presentation";
        public const string ODS = "application/vnd.oasis.opendocument.spreadsheet";
        public const string ODT = "application/vnd.oasis.opendocument.text";
        public const string OGA = "audio/ogg";
        public const string OGV = "video/ogg";
        public const string OGX = "application/ogg";
        public const string OPUS = "audio/opus";
        public const string OTF = "font/otf";
        public const string PNG = "image/png";
        public const string PDF = "application/pdf";
        public const string PHP = "application/x-httpd-php";
        public const string PPT = "application/vnd.ms-powerpoint";
        public const string PPTX = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
        public const string RAR = "application/vnd.rar";
        public const string RTF = "application/rtf";
        public const string SH = "application/x-sh";
        public const string SVG = "image/svg+xml";
        public const string SWF = "application/x-shockwave-flash";
        public const string TAR = "application/x-tar";
        public const string TIFF = "image/tiff";
        public const string TS = "video/mp2t";
        public const string TTF = "font/ttf";
        public const string TXT = "text/plain";
        public const string VSD = "application/vnd.visio";
        public const string WAV = "audio/wav";
        public const string WEBA = "audio/webm";
        public const string WEBM = "video/webm";
        public const string WEBP = "image/webp";
        public const string WOFF = "font/woff";
        public const string WOFF2 = "font/woff2";
        public const string XHTML = "application/xhtml+xml";
        public const string XLS = "application/vnd.ms-excel";
        public const string XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        public const string XML = "application/xml";
        public const string XUL = "application/vnd.mozilla.xul+xml";
        public const string ZIP = "application/zip";
        public const string _3GP = "video/3gpp";
        public const string _3G2 = "video/3gpp2";
        public const string _7Z = "application/x-7z-compressed";
    }
}
